all = imread('ruch1.jpg');
tlo = imread('ruch0.jpg');
odj1= imsubtract(all,tlo);
odj2= imsubtract(tlo,all);
imwrite(odj1, 'odjêcie1.jpg');
imwrite(odj2, 'odjêcie2.jpg');
reka = imadd(odj1, odj2);
imwrite(reka, 'etap1-reka.jpg');
binarny = im2bw(reka, 0.05);
filtrowany= medfilt2(binarny, [3 3]);
imwrite(binarny, 'etap2-binarny.jpg'); 
imwrite(filtrowany, 'etap3-szumy.jpg');
se = strel('square',2);
proba3 = medfilt2(imerode(filtrowany, se), [3 3]);
imwrite(proba3, 'etap4-morfologia.jpg');
wypelnianie = imfill(proba3, 'holes');
imwrite(wypelnianie, 'etap5-wypelnianie.jpg');
krawedz1 = edge(wypelnianie, 'sobel');
krawedz2 = edge(wypelnianie, 'canny');
imwrite(krawedz1, 'etap6b-krawedziesobela.jpg');
imwrite(krawedz2, 'etap6-krawedziecannego.jpg');
krawedz = uint8(krawedz2)*255;
reszta = rgb2gray(all);
ostateczny = imadd(krawedz, reszta);
imwrite(ostateczny, 'ostateczny.jpg');
figure;
imshow(ostateczny);